### PR TITLE
chore: update workflows after branch rename

### PR DESCRIPTION
**Pull request by thomasheartman**

### CODE REVIEW

**Comment by thomasheartman** [comment]
[Rename GitHub default branches from master to main](https://trello.com/c/Ey6olr8s/669-rename-github-default-branches-from-master-to-main)

**Review by RikudouSage — APPROVED** [review]

**Comment by RikudouSage** [comment]
Thanks, should I do the same for https://github.com/Unleash/unleash-client-symfony or will someone else send a PR?

**Comment by thomasheartman** [comment]
Yes, please! I'm sorry, it seems I forgot to do it for that repo. If you could do it, that'd be great! 😄  Thank you! 🙏🏼

**Comment by thomasheartman** [comment]
Update: [Here's the symfony pull request](https://github.com/Unleash/unleash-client-symfony/pull/6)!

**Pull request merged**
