### PR TITLE
Add support for psr/http-message:^2.0

### PR DESCRIPTION
**Pull request by W0rma**
# Description

[Release notes for `psr/http-message:^2.0`](https://github.com/php-fig/http-message/releases/tag/2.0)

## Type of change

Please delete options that are not relevant.

- [x] Dependency update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [x] Unit tests
- [ ] Spec Tests
- [ ] Integration tests / Manual Tests

### CODE REVIEW

**Comment by RikudouSage** [comment]
It doesn't seem to pass tests.

**Comment by W0rma** [comment]
> It doesn't seem to pass tests.

Sorry, there was a typo.

Should be fixed now. I was able to run the test suite locally.

**Comment by RikudouSage** [comment]
Can you make it accept ^1.0 as well? Also remove the changes from StringStream, I feel like it adds unnecessary BC break, the only change that's needed is adding `string` return type to `__toString()`.

**Comment by W0rma** [comment]
> Can you make it accept ^1.0 as well? Also remove the changes from StringStream

I've just removed my changes.

**Comment by RikudouSage** [comment]
As mentioned before, the only change that's needed is adding string return type to __toString(), otherwise it doesn't pass. If you rebase the current main branch, additional tests would be ran that should catch the error.

**Comment by Andreas-Halemba** [comment]
Are here any updates on this?

**Comment by W0rma** [comment]
> As mentioned before, the only change that's needed is adding string return type to __toString(), otherwise it doesn't pass.

@RikudouSage I have just rebased and the tests are still green.

I don't see how the requested change should be related to the changeset of this MR.

Please let me know if you still want me to change this method signature.

**Comment by RikudouSage** [comment]
Hm, that's weird, I'll check it out today.

**Comment by RikudouSage** [comment]
Hm, it seems to work because PHP internally adds `string` return type to the `__toString()` method, but I'd like it explicit anyway, because as of now it doesn't follow Liskov substitution principle, even though PHP changes it internally to be compatible.

I'm talking about the method `\Unleash\Client\Helper\StringStream::__toString()`.

**Comment by W0rma** [comment]
@RikudouSage I just added the return type as suggested.

**Review by RikudouSage — APPROVED** [review]
Thanks!

**Pull request merged**
